spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/learn-web-db
    username: root
    password: Harsha@123
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true